# Generated by Django 2.2.4 on 2019-11-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='chead0',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='blog',
            name='chead1',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='blog',
            name='chead2',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
