# Generated by Django 2.2.4 on 2019-11-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191101_0734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogpost',
        ),
    ]
