# Generated by Django 2.2.4 on 2019-10-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191013_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
